# 2.1.1 Getting Started

In [51]:
import torch
#Create tensor
x=torch.arange(12,dtype=torch.float32)
print(x)

#number of elements: 
n=x.numel()
print(n)

print(x.shape)

Y=x.reshape(3,4)
print(y)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
12
torch.Size([12])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


# 2.1.2 Indexing and Slicing

In [52]:
#select last row:
print(Y[-1])
#select 2nd and 3d row (1 to 3)
print(Y[1:3])

#alter rows/cols
Y[:2,:]=12
print(Y)

tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


# 2.1.3 Operations

In [53]:
#Elementwise op -> e^y(i,j) for all y(i,j) belonging in the matrix
print(torch.exp(Y))

#binary operators / f:R,R->R 
u=torch.tensor([1,2,4,8])
v=torch.tensor([2,2,2,2])

print(u-v)

X=torch.arange(12,dtype=torch.float32).reshape(3,4)
Y=torch.tensor([[12,13,14,15],[16,17,18,19],[20,21,22,23]])

#Concat along row axis
Z=torch.cat((X,Y),dim=0)
print(Z)

#check equality
print(X==Y)

#sumall elements in a tensor
sum=X.sum()
print(sum)

tensor([[162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [  2980.9580,   8103.0840,  22026.4648,  59874.1406]])
tensor([-1,  0,  2,  6])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor(66.)


# 2.1.4 Broadcasting

In [54]:
#used to perform elementwise binary ops on elements of different size
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
print(a+b)


tensor([[0, 1],
        [1, 2],
        [2, 3]])


# 2.1.5 Saving Memory

In [ ]:
before = id(Y)
Y = Y + X
r=id(Y) == before
print(r)
# so we deference the previous Y but we allocate use a fresh new space, allocating further (unnecessary) memory.
# therefore, we want to perform this updates IN PLACE, like so:
before=id(Y)
Y[:]=Y+X #or Y+=X
r=id(Y)==before 
print(r)

False
True


# 2.1.6 Conversion to other python objects

In [ ]:
A=X.numpy()
B=torch.from_numpy(A)