# 2.3.1 Scalars

In [97]:
import torch

#scalars are implemented by single-value tensors

x=torch.tensor(3.0)
y=torch.tensor(5.0)

print(x+y)

tensor(8.)


# 2.3.2 Vectors

In [98]:
#denoted by bold lowercase letters (e.g. bold(x))

x=torch.arange(3)
print(x)
# we access the tensor via indexing.
print(x[1])

print(x.shape)

tensor([0, 1, 2])
tensor(1)
torch.Size([3])


# 2.3.3 Matrices    

In [99]:
#2nd order tensors
A=torch.arange(6).reshape(3,2)
print(A)

#transp:
print(A.T)

#symmetric: A=A^T, with A square matrix (m x n where m=n)
A=torch.zeros(4,4)

if torch.equal(A,A.T):
    print("A is symmetrical")
else:
    print("A is NOT symmetrical")



tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor([[0, 2, 4],
        [1, 3, 5]])
A is symmetrical


# 2.3.5 Basic Properties of Tensors Arithmetic

In [100]:
#elementwise ops produce outputs that have the same size as their operands.

A=torch.arange(6,dtype=torch.float32).reshape(2,3)
B=A.clone() #allocation of new memory
print(A)
print(A+B)

#elementwise product is called Hadamard product O.
print(A*B)

#scalar+Tensor v scalar*Tensor do not change Tensor's shape.
a=2
X=torch.arange(24).reshape(2,3,4)
print(2*X)


tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])
tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])


# 2.3.6 Reduction

In [101]:
#sum of tensor's elements:
x=torch.arange(3)
print(x.sum())

tensor(3)


# 2.3.13 Exercises

In [ ]:
x=torch.arange(24,dtype=torch.float32).reshape(2,3,4)
print(len(x))

print(torch.linalg.norm(x))

x.sum(axis=0).size()

x=torch.ones(2,3,6)

print(torch.linalg.norm(x))




2
tensor(65.7571)
tensor(6.)
